// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oxby7mL3tramyYPU9d77Uw
// Component: Ipt2bB5a3Io7

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Offer2 from "../../Offer2"; // plasmic-import: qirFgpOYNvLFFY6/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_offer_theme_1_component_css from "../offer_theme_1_component/plasmic_offer_theme_1_component.module.css"; // plasmic-import: 8JEXBqjqN3wJGHTHZ9qf9H/projectcss
import projectcss from "./plasmic_copy_of_feed_presell_ai.module.css"; // plasmic-import: oxby7mL3tramyYPU9d77Uw/projectcss
import sty from "./PlasmicOfferTheme2.module.css"; // plasmic-import: Ipt2bB5a3Io7/css

createPlasmicElementProxy;

export type PlasmicOfferTheme2__VariantMembers = {};
export type PlasmicOfferTheme2__VariantsArgs = {};
type VariantPropType = keyof PlasmicOfferTheme2__VariantsArgs;
export const PlasmicOfferTheme2__VariantProps = new Array<VariantPropType>();

export type PlasmicOfferTheme2__ArgsType = {};
type ArgPropType = keyof PlasmicOfferTheme2__ArgsType;
export const PlasmicOfferTheme2__ArgProps = new Array<ArgPropType>();

export type PlasmicOfferTheme2__OverridesType = {
  root?: p.Flex<"div">;
  offer2?: p.Flex<typeof Offer2>;
};

export interface DefaultOfferTheme2Props {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOfferTheme2__RenderFunc(props: {
  variants: PlasmicOfferTheme2__VariantsArgs;
  args: PlasmicOfferTheme2__ArgsType;
  overrides: PlasmicOfferTheme2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_offer_theme_1_component_css.plasmic_tokens,
        sty.root
      )}
    >
      <Offer2
        data-plasmic-name={"offer2"}
        data-plasmic-override={overrides.offer2}
        className={classNames("__wab_instance", sty.offer2)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "offer2"],
  offer2: ["offer2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  offer2: typeof Offer2;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOfferTheme2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOfferTheme2__VariantsArgs;
    args?: PlasmicOfferTheme2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOfferTheme2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicOfferTheme2__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicOfferTheme2__ArgProps,
          internalVariantPropNames: PlasmicOfferTheme2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOfferTheme2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOfferTheme2";
  } else {
    func.displayName = `PlasmicOfferTheme2.${nodeName}`;
  }
  return func;
}

export const PlasmicOfferTheme2 = Object.assign(
  // Top-level PlasmicOfferTheme2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    offer2: makeNodeComponent("offer2"),

    // Metadata about props expected for PlasmicOfferTheme2
    internalVariantProps: PlasmicOfferTheme2__VariantProps,
    internalArgProps: PlasmicOfferTheme2__ArgProps
  }
);

export default PlasmicOfferTheme2;
/* prettier-ignore-end */
