// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oxby7mL3tramyYPU9d77Uw
// Component: mEVUo6Ws0yF3

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import OfferTheme1Component from "../../OfferTheme1Component"; // plasmic-import: PvFaq5F-Pvxa/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_offer_theme_1_component_css from "../offer_theme_1_component/plasmic_offer_theme_1_component.module.css"; // plasmic-import: 8JEXBqjqN3wJGHTHZ9qf9H/projectcss
import projectcss from "./plasmic_copy_of_feed_presell_ai.module.css"; // plasmic-import: oxby7mL3tramyYPU9d77Uw/projectcss
import sty from "./PlasmicOfferTheme1.module.css"; // plasmic-import: mEVUo6Ws0yF3/css

createPlasmicElementProxy;

export type PlasmicOfferTheme1__VariantMembers = {};
export type PlasmicOfferTheme1__VariantsArgs = {};
type VariantPropType = keyof PlasmicOfferTheme1__VariantsArgs;
export const PlasmicOfferTheme1__VariantProps = new Array<VariantPropType>();

export type PlasmicOfferTheme1__ArgsType = {};
type ArgPropType = keyof PlasmicOfferTheme1__ArgsType;
export const PlasmicOfferTheme1__ArgProps = new Array<ArgPropType>();

export type PlasmicOfferTheme1__OverridesType = {
  root?: p.Flex<"div">;
  offerTheme1Component?: p.Flex<typeof OfferTheme1Component>;
};

export interface DefaultOfferTheme1Props {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOfferTheme1__RenderFunc(props: {
  variants: PlasmicOfferTheme1__VariantsArgs;
  args: PlasmicOfferTheme1__ArgsType;
  overrides: PlasmicOfferTheme1__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_offer_theme_1_component_css.plasmic_tokens,
            sty.root
          )}
        >
          <OfferTheme1Component
            data-plasmic-name={"offerTheme1Component"}
            data-plasmic-override={overrides.offerTheme1Component}
            className={classNames("__wab_instance", sty.offerTheme1Component)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "offerTheme1Component"],
  offerTheme1Component: ["offerTheme1Component"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  offerTheme1Component: typeof OfferTheme1Component;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOfferTheme1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOfferTheme1__VariantsArgs;
    args?: PlasmicOfferTheme1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOfferTheme1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicOfferTheme1__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicOfferTheme1__ArgProps,
          internalVariantPropNames: PlasmicOfferTheme1__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOfferTheme1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOfferTheme1";
  } else {
    func.displayName = `PlasmicOfferTheme1.${nodeName}`;
  }
  return func;
}

export const PlasmicOfferTheme1 = Object.assign(
  // Top-level PlasmicOfferTheme1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    offerTheme1Component: makeNodeComponent("offerTheme1Component"),

    // Metadata about props expected for PlasmicOfferTheme1
    internalVariantProps: PlasmicOfferTheme1__VariantProps,
    internalArgProps: PlasmicOfferTheme1__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicOfferTheme1;
/* prettier-ignore-end */
