// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: oxby7mL3tramyYPU9d77Uw
// Component: HN9J7roJyTPE

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { DataFetcher } from "@plasmicpkgs/plasmic-query"; // plasmic-import: ae7V86eNoXA/codeComponent
import NavLogoOnly from "../../NavLogoOnly"; // plasmic-import: AH-KmfMOh5r7/component
import SqueezeForm from "../../SqueezeForm"; // plasmic-import: pECbqkQwbRcU/component
import { PlasmicHead } from "@plasmicapp/react-web"; // plasmic-import: vjeAXjQ_02/codeComponent
import { Embed } from "@plasmicpkgs/plasmic-basic-components"; // plasmic-import: PKldDYkH42/codeComponent

import { useScreenVariants as useScreenVariantscylgZgvvaF7G } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: CYLGZgvvaF7G/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_offer_theme_1_component_css from "../offer_theme_1_component/plasmic_offer_theme_1_component.module.css"; // plasmic-import: 8JEXBqjqN3wJGHTHZ9qf9H/projectcss
import projectcss from "./plasmic_copy_of_feed_presell_ai.module.css"; // plasmic-import: oxby7mL3tramyYPU9d77Uw/projectcss
import sty from "./PlasmicSqueeze1.module.css"; // plasmic-import: HN9J7roJyTPE/css

createPlasmicElementProxy;

export type PlasmicSqueeze1__VariantMembers = {};
export type PlasmicSqueeze1__VariantsArgs = {};
type VariantPropType = keyof PlasmicSqueeze1__VariantsArgs;
export const PlasmicSqueeze1__VariantProps = new Array<VariantPropType>();

export type PlasmicSqueeze1__ArgsType = {};
type ArgPropType = keyof PlasmicSqueeze1__ArgsType;
export const PlasmicSqueeze1__ArgProps = new Array<ArgPropType>();

export type PlasmicSqueeze1__OverridesType = {
  root?: p.Flex<"div">;
  httpRestApiFetcher?: p.Flex<typeof DataFetcher>;
  navLogoOnly?: p.Flex<typeof NavLogoOnly>;
  productDetails2?: p.Flex<"div">;
  sThumbail?: p.Flex<typeof p.PlasmicImg>;
  sH1?: p.Flex<"div">;
  sH2?: p.Flex<"div">;
  sH3?: p.Flex<"div">;
  head?: p.Flex<typeof PlasmicHead>;
  productDetails?: p.Flex<"div">;
  embedHtml?: p.Flex<typeof Embed>;
};

export interface DefaultSqueeze1Props {}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSqueeze1__RenderFunc(props: {
  variants: PlasmicSqueeze1__VariantsArgs;
  args: PlasmicSqueeze1__ArgsType;
  overrides: PlasmicSqueeze1__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantscylgZgvvaF7G()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicSqueeze1.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicSqueeze1.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicSqueeze1.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_offer_theme_1_component_css.plasmic_tokens,
            sty.root
          )}
          id={(() => {
            try {
              return $ctx.params.slug;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()}
        >
          <DataFetcher
            data-plasmic-name={"httpRestApiFetcher"}
            data-plasmic-override={overrides.httpRestApiFetcher}
            className={classNames("__wab_instance", sty.httpRestApiFetcher)}
            dataName={"fetchDyanamicData" as const}
            errorDisplay={
              <ph.DataCtxReader>
                {$ctx => "Error fetching data"}
              </ph.DataCtxReader>
            }
            headers={{
              "Content-Type": "application/json",
              Accept: "application/json",
              Authorization: "Bearer keyVDvhyVSx5Ntbl3"
            }}
            loadingDisplay={
              <ph.DataCtxReader>{$ctx => "Loading..."}</ph.DataCtxReader>
            }
            method={"GET" as const}
            noLayout={false}
            url={(() => {
              try {
                return (
                  "https://api.airtable.com/v0/appmM1mMqcDvugXhY/PlasmicCMS?filterByFormula=slug=" +
                  "'" +
                  $ctx.params.slug +
                  "'"
                );
              } catch (e) {
                if (
                  e instanceof TypeError ||
                  e?.plasmicType === "PlasmicUndefinedDataError"
                ) {
                  return "https://api.airtable.com/v0/appmM1mMqcDvugXhY/PlasmicCMS?filterByFormula=slug=";
                }
                throw e;
              }
            })()}
          >
            <ph.DataCtxReader>
              {$ctx => (
                <React.Fragment>
                  <NavLogoOnly
                    data-plasmic-name={"navLogoOnly"}
                    data-plasmic-override={overrides.navLogoOnly}
                    className={classNames("__wab_instance", sty.navLogoOnly)}
                  />

                  <div
                    data-plasmic-name={"productDetails2"}
                    data-plasmic-override={overrides.productDetails2}
                    className={classNames(projectcss.all, sty.productDetails2)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.columns__hS2Jt)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__z7J80
                        )}
                      >
                        <p.PlasmicImg
                          data-plasmic-name={"sThumbail"}
                          data-plasmic-override={overrides.sThumbail}
                          alt={""}
                          className={classNames(sty.sThumbail)}
                          displayHeight={"175px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"196px" as const}
                          loading={"lazy" as const}
                          src={(() => {
                            try {
                              return $ctx.fetchDyanamicData.records[0].fields
                                .sThumbail[0].url;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__mfzoc
                        )}
                      >
                        <div
                          data-plasmic-name={"sH1"}
                          data-plasmic-override={overrides.sH1}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.sH1
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $ctx.fetchDyanamicData.records[0].fields
                                  .sH1;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Product Name Here";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          data-plasmic-name={"sH2"}
                          data-plasmic-override={overrides.sH2}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.sH2
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $ctx.fetchDyanamicData.records[0].fields
                                  .sH2;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Enter some text";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                        <div
                          data-plasmic-name={"sH3"}
                          data-plasmic-override={overrides.sH3}
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.sH3
                          )}
                        >
                          <React.Fragment>
                            {(() => {
                              try {
                                return $ctx.fetchDyanamicData.records[0].fields
                                  .sH3;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return "Enter some text";
                                }
                                throw e;
                              }
                            })()}
                          </React.Fragment>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__t2Zkm)}
                  >
                    <SqueezeForm
                      className={classNames(
                        "__wab_instance",
                        sty.squeezeForm__gtMuj
                      )}
                    />
                  </div>
                  <PlasmicHead
                    data-plasmic-name={"head"}
                    data-plasmic-override={overrides.head}
                    className={classNames("__wab_instance", sty.head)}
                    description={(() => {
                      try {
                        return $ctx.fetchDyanamicData.fields[
                          "Step 2 SEO Description"
                        ];
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    image={(() => {
                      try {
                        return undefined;
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                    title={(() => {
                      try {
                        return $ctx.fetchDyanamicData.fields[
                          "Step 2 SEO Title"
                        ];
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__rTyTm)}
                    >
                      {true ? (
                        <div
                          data-plasmic-name={"productDetails"}
                          data-plasmic-override={overrides.productDetails}
                          className={classNames(
                            projectcss.all,
                            sty.productDetails
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.column__eJhs1
                            )}
                          >
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.columns__dh5GK
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column___3Elpq
                                )}
                              >
                                <p.PlasmicImg
                                  alt={""}
                                  className={classNames(sty.img__liFQd)}
                                  displayHeight={"175px" as const}
                                  displayMaxHeight={"none" as const}
                                  displayMaxWidth={"100%" as const}
                                  displayMinHeight={"0" as const}
                                  displayMinWidth={"0" as const}
                                  displayWidth={
                                    hasVariant(
                                      globalVariants,
                                      "screen",
                                      "mobileOnly"
                                    )
                                      ? ("170px" as const)
                                      : ("196px" as const)
                                  }
                                  loading={"lazy" as const}
                                  src={(() => {
                                    try {
                                      return $ctx.fetchDyanamicData.fields
                                        .sThumbail[0].url;
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return undefined;
                                      }
                                      throw e;
                                    }
                                  })()}
                                />
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column___5D4Sh
                                )}
                              >
                                {(
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                ) ? (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__d4CmG
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return $ctx.fetchDyanamicData.fields
                                            .sH1;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Enter some text";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                ) : null}
                                {(
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                ) ? (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text___79L3
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return $ctx.fetchDyanamicData.fields
                                            .sH2;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "undefine";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                ) : null}
                                {(
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                ) ? (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__ffqF
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return $ctx.fetchDyanamicData.fields
                                            .sH1;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Enter some text";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                ) : null}
                                {(
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? true
                                    : true
                                ) ? (
                                  <div
                                    className={classNames(
                                      projectcss.all,
                                      projectcss.__wab_text,
                                      sty.text__r66UP
                                    )}
                                  >
                                    <React.Fragment>
                                      {(() => {
                                        try {
                                          return $ctx.fetchDyanamicData.fields
                                            .sH2;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "Enter some text";
                                          }
                                          throw e;
                                        }
                                      })()}
                                    </React.Fragment>
                                  </div>
                                ) : null}
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__cjEaD
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return $ctx.fetchDyanamicData.fields
                                          .sH3;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Enter some text";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                              </div>
                            </p.Stack>
                          </div>
                        </div>
                      ) : null}
                      <SqueezeForm
                        className={classNames(
                          "__wab_instance",
                          sty.squeezeForm__klYk5
                        )}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tmWpp
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__i2BFq)}
                            displayHeight={"56px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"100%" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"auto" as const}
                            loading={"lazy" as const}
                            src={(() => {
                              try {
                                return $ctx.fetchDyanamicData.fields.logo[0]
                                  .url;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          />
                        </div>
                      ) : null}
                    </div>
                  ) : null}
                  <Embed
                    data-plasmic-name={"embedHtml"}
                    data-plasmic-override={overrides.embedHtml}
                    className={classNames("__wab_instance", sty.embedHtml)}
                    code={(() => {
                      try {
                        return $ctx.fetchDyanamicData.records[0].fields[
                          "scripts (from Brands)"
                        ][0];
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                  />
                </React.Fragment>
              )}
            </ph.DataCtxReader>
          </DataFetcher>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "httpRestApiFetcher",
    "navLogoOnly",
    "productDetails2",
    "sThumbail",
    "sH1",
    "sH2",
    "sH3",
    "head",
    "productDetails",
    "embedHtml"
  ],
  httpRestApiFetcher: [
    "httpRestApiFetcher",
    "navLogoOnly",
    "productDetails2",
    "sThumbail",
    "sH1",
    "sH2",
    "sH3",
    "head",
    "productDetails",
    "embedHtml"
  ],
  navLogoOnly: ["navLogoOnly"],
  productDetails2: ["productDetails2", "sThumbail", "sH1", "sH2", "sH3"],
  sThumbail: ["sThumbail"],
  sH1: ["sH1"],
  sH2: ["sH2"],
  sH3: ["sH3"],
  head: ["head"],
  productDetails: ["productDetails"],
  embedHtml: ["embedHtml"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  httpRestApiFetcher: typeof DataFetcher;
  navLogoOnly: typeof NavLogoOnly;
  productDetails2: "div";
  sThumbail: typeof p.PlasmicImg;
  sH1: "div";
  sH2: "div";
  sH3: "div";
  head: typeof PlasmicHead;
  productDetails: "div";
  embedHtml: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSqueeze1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSqueeze1__VariantsArgs;
    args?: PlasmicSqueeze1__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSqueeze1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicSqueeze1__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSqueeze1__ArgProps,
          internalVariantPropNames: PlasmicSqueeze1__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSqueeze1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSqueeze1";
  } else {
    func.displayName = `PlasmicSqueeze1.${nodeName}`;
  }
  return func;
}

export const PlasmicSqueeze1 = Object.assign(
  // Top-level PlasmicSqueeze1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    httpRestApiFetcher: makeNodeComponent("httpRestApiFetcher"),
    navLogoOnly: makeNodeComponent("navLogoOnly"),
    productDetails2: makeNodeComponent("productDetails2"),
    sThumbail: makeNodeComponent("sThumbail"),
    sH1: makeNodeComponent("sH1"),
    sH2: makeNodeComponent("sH2"),
    sH3: makeNodeComponent("sH3"),
    head: makeNodeComponent("head"),
    productDetails: makeNodeComponent("productDetails"),
    embedHtml: makeNodeComponent("embedHtml"),

    // Metadata about props expected for PlasmicSqueeze1
    internalVariantProps: PlasmicSqueeze1__VariantProps,
    internalArgProps: PlasmicSqueeze1__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Squeeze",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSqueeze1;
/* prettier-ignore-end */
